# Core Infrastructure App-of-Apps
# Base platform components deployed for all experiments
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: core-infrastructure
  namespace: argocd
  labels:
    layer: core
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    # TLS/Certificate management
    - repoURL: https://github.com/illMadeCoder/illm-k8s-lab.git
      targetRevision: HEAD
      path: argocd-apps/cert-manager
      directory:
        recurse: false
        include: 'cert-manager*.yaml'

    # Gateway/Ingress
    - repoURL: https://github.com/illMadeCoder/illm-k8s-lab.git
      targetRevision: HEAD
      path: argocd-apps/gateway-api
      directory:
        recurse: false
        include: 'gateway-api.yaml'

    # Observability - Prometheus/Grafana
    - repoURL: https://github.com/illMadeCoder/illm-k8s-lab.git
      targetRevision: HEAD
      path: argocd-apps/observability
      directory:
        recurse: false
        include: 'kube-prometheus-stack.yaml'

    # Observability - Loki (logs)
    - repoURL: https://github.com/illMadeCoder/illm-k8s-lab.git
      targetRevision: HEAD
      path: argocd-apps/loki
      directory:
        recurse: false
        include: 'loki.yaml'

    # Observability - Promtail (log shipper)
    - repoURL: https://github.com/illMadeCoder/illm-k8s-lab.git
      targetRevision: HEAD
      path: argocd-apps/promtail
      directory:
        recurse: false
        include: 'promtail.yaml'

    # Observability - OpenTelemetry
    - repoURL: https://github.com/illMadeCoder/illm-k8s-lab.git
      targetRevision: HEAD
      path: argocd-apps/otel-collector
      directory:
        recurse: false
        include: 'otel-collector.yaml'

    # Artifact storage
    - repoURL: https://github.com/illMadeCoder/illm-k8s-lab.git
      targetRevision: HEAD
      path: argocd-apps/minio
      directory:
        recurse: false
        include: 'minio.yaml'

    # Workflow engine
    - repoURL: https://github.com/illMadeCoder/illm-k8s-lab.git
      targetRevision: HEAD
      path: argocd-apps/argo-workflows
      directory:
        recurse: false
        include: 'argo-workflows.yaml'

    # Load testing (k6)
    - repoURL: https://github.com/illMadeCoder/illm-k8s-lab.git
      targetRevision: HEAD
      path: argocd-apps/k6
      directory:
        recurse: false
        include: 'k6-operator.yaml'

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
