---
# Certificate for Grafana (using self-signed issuer for local testing)
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-tls
  namespace: observability
spec:
  secretName: grafana-tls-secret
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
  dnsNames:
    - grafana.local
    - localhost
  ipAddresses:
    - 127.0.0.1
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
---
# Gateway with TLS listener for HTTPS
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: https-gateway
  namespace: default
spec:
  gatewayClassName: eg
  listeners:
    - name: https
      protocol: HTTPS
      port: 443
      tls:
        mode: Terminate
        certificateRefs:
          - name: grafana-tls-secret
            namespace: observability
            kind: Secret
      allowedRoutes:
        namespaces:
          from: All
---
# ReferenceGrant to allow Gateway to use cert from observability namespace
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allow-gateway-grafana-cert
  namespace: observability
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: Gateway
      namespace: default
  to:
    - group: ""
      kind: Secret
      name: grafana-tls-secret
---
# HTTPRoute to route traffic to Grafana over HTTPS
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: grafana
  namespace: observability
spec:
  parentRefs:
    - name: https-gateway
      namespace: default
  hostnames:
    - grafana.local
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: kube-prometheus-stack-grafana
          port: 80
