# Crossplane Providers AWS (Wave 4)
# AWS family + all individual AWS providers
# Depends on: crossplane-providers-azure
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-providers-aws
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: hub
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/illMadeCoder/illm-k8s-ai-labs.git
    targetRevision: HEAD
    path: experiments/components/infrastructure/crossplane-providers/aws
    directory:
      recurse: false
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
